stages:
  create_model:
    cmd: python scripts/create_model.py
  train:
    cmd: python scripts/train_model.py
    deps:
      - PetImages/
      - src/
      - scripts/train_model.py
    outs:
      - models/model.pt
    params: []
  evaluate:
    cmd: python scripts/evaluate_model.py
    deps:
      - models/model.pt
      - src/
      - scripts/evaluate_model.py
    outs:
      - metrics/metrics.json
    params: []
    