stages:
  create_model:
    cmd: python scripts/create_model.py
  train:
    cmd: python scripts/train_model.py
    deps:
      - PetImages/
      - src/
      - scripts/train_model.py
    outs:
      - models/model.pt
    params: []
  evaluate:
    cmd: python scripts/evaluate_model.py
    deps:
      - models/model.pt
      - src/
      - scripts/evaluate_model.py
    outs:
      - metrics/metrics.json
    params: []

plots:
  - metrics/metrics.json:
      template: simple
      x: epoch
      y:
        - train_loss
        - val_loss
        - train_accuracy
        - val_accuracy
        - val_precision
        - val_recall
        - val_f1_score
      title: "Training Metrics"
  - val_f1_score vs val_recall:
      template: confusion
      x: val_f1_score
      y:
        metrics/metrics.json: val_recall
  - num_epochs vs val_precision:
      template: confusion
      x: num_epochs
      y:
        metrics/metrics.json:
          - val_precision
          - val_recall


